In [1]:
# 端到端的开源的机器学习框架
# 机器学习生态系统

# 
# 2011：Disbelief
# 2017.2 Tensorflow1.0  高层API、将Keras库整合进启动
# 

import tensorflow as tf
# keras有两类keras。我们可以自己进行选择，使用ts-keras还是keras。
# import keras
from tensorflow import keras
import numpy as np

# 我们先进行打印一下我们所有的依赖库的版本号
print(tf.__version__)
# 
print("Tensorflow运行在：",tf.executing_eagerly())

2.5.0
Tensorflow运行在： True


In [4]:
# 我们来学习一下张量的运算

# 张量加减乘除运算、幂运算、对数运算、矩阵运算
# 基本数学运算
# tf.add(x,y)  #将x和y逐个元素相加
# tf.subtract(x,y)  #将x和y逐个元素相减
# tf.multiply(x,y)  #将x和y逐个元素相乘
# tf.divide(x,y)    #将x和y逐个元素相除
# tf.math.mod(x,y)    #将x和y逐个元素取模

# 减法、乘法、除法运算也都是这两个张量的逐个元素的运算，并且要求各个张量中的元素数据类型都一致。
a1 = tf.constant([0,1,2])
b1 = tf.constant([3,4,5])
tf.add(a1,b1 )


<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 5, 7], dtype=int32)>

In [5]:

a1 = tf.constant([0,1,2])
b1 = tf.constant([3,4,5])
tf.subtract(a1,b1 )

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-3, -3, -3], dtype=int32)>

In [6]:
a1 = tf.constant([0,1,2])
b1 = tf.constant([3,4,5])
tf.multiply(a1,b1 )

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 0,  4, 10], dtype=int32)>

In [7]:
a1 = tf.constant([0,1,2])
b1 = tf.constant([3,4,5])
tf.divide(a1,b1 )

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.  , 0.25, 0.4 ])>

In [8]:
a1 = tf.constant([0,1,2])
b1 = tf.constant([3,4,5])
tf.math.mod(a1,b1 )

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 1, 2], dtype=int32)>

In [14]:
# 基本数学运算

# 幂指数、指数、对数运算
# tf.pow(x,y)  #将x和y逐个元素相加
# tf.square(x,y)  #将x和y逐个元素相减
# tf.sqrt(x,y)  #将x和y逐个元素相乘
# tf.exp(x,y)    #将x和y逐个元素相除
# tf.math.log(x,y)    #将x和y逐个元素取模

x = tf.range(4)
x
tf.pow(x,2)

# 二维张量的运算
x1 = tf.constant([[2,2],[3,3]])
x2 = tf.constant([[8,16],[2,3]])
tf.pow(x1,x2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  256, 65536],
       [    9,    27]], dtype=int32)>