In [1]:
# 端到端的开源的机器学习框架
# 机器学习生态系统

# 
# 2011：Disbelief
# 2017.2 Tensorflow1.0  高层API、将Keras库整合进启动
# 

import tensorflow as tf
# keras有两类keras。我们可以自己进行选择，使用ts-keras还是keras。
# import keras
from tensorflow import keras
import numpy as np

# 我们先进行打印一下我们所有的依赖库的版本号
print(tf.__version__)
# 
print("Tensorflow运行在：",tf.executing_eagerly())

2.5.0
Tensorflow运行在： True


In [2]:
# 如果要在Tensorflow2.x中显示调用1.x的代码。需要使用下面两行代码
# import tensorflow.compat.v1 as tf
# tf.disable_v2_behavior()
# Tensorflow2.0的环境中，运行Tensorflow1.x的代码。常常出现错误提示
# a = tf.constant(2,name="input_a")
# b = tf.constant(3,name="input_a")
# c = tf.add(a,b,name="add_c")

# session = tf.Session()
# print(session.run(c))
# session.close()
# ---------------------------------------------------------------------------
# AttributeError                            Traceback (most recent call last)
# <ipython-input-3-5810165b582a> in <module>
#       4 c = tf.add(a,b,name="add_c")
#       5 
# ----> 6 session = tf.Session()
#       7 print(session.run(c))
#       8 session.close()

# AttributeError: module 'tensorflow' has no attribute 'Session'
# 出在
# Tensorflow2.X无法运行1.x的代码怎么办？
# 如上，我们可以通过
# import tensorflow.compat.v1 as tf
# tf.disable_v2_behavior()

In [3]:
# Tensorflow中Tensor表示张量

value = tf.constant([[1,2],[3,4]])
# Tensor张量中。shape表示张量形状。

In [4]:
# Tensorflow所有的张量多可以tensor.numpy()方法得到对应的数组
# TODO 这个方法已经被废除了？
# value.numpy()

print(type(value))
print(value)

<class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [5]:
# 张量可以是一个数组
value = tf.constant(1.0)
tf.print(value)
# 
# tf.constant(1.)

# tf.constant(1.0,dtype=tf.float64)

1


In [6]:
# Numpy数组作为张量参数
tf.constant(np.array([1,2]))
tf.constant(np.array([1.0,2.0]))
tf.constant(np.array([1.0,2.0]),dtype=tf.float32)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [7]:
# tf.constant的函数，改变张量中元素的数据类型
# tf.cast(x,dtype)

a = tf.constant(np.array([1,2]))
b = tf.cast(a,dtype=tf.float32)
b.dtype

# 数据类型转换
# TODO 张量的数据和2.0有很大的不同
a = tf.constant(123456789,dtype=tf.int32)
tf.cast(a,tf.int16)

# 数据类型转换
# TODO 张量的数据和2.0有很大的不同
a = tf.constant([-1,0,1,2])
tf.cast(a,tf.bool)

# 数据类型转换
# 参数类型为字符串
tf.constant("Hello")

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello'>

In [8]:
# tf.convert_to_tensor(数组/列表/数字/布尔类型/字符串)
na = np.arange(12).reshape(3,4)
print(na)
ta = tf.convert_to_tensor(na)
type(na)
type(ta)

# is_tensor函数
tf.is_tensor(ta)

# isinstance函数
isinstance(ta,tf.Tensor)
isinstance(na,np.ndarray)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


True

In [9]:
# 张量生成
# 全0张量
# 全1张量

# 全0张量
# tf.zeros(shape,dtype=tf.float32)
# tf.ones(shape,dtype=tf.float32) 
# 默认的数据类型就是float32
tf.zeros(shape=(2,1),dtype=tf.float32)

tf.zeros([6])

# 创建素有元素值都相同的张量-tf.fill()方法。
tf.fill([2,3],9)
# tf.print(fillTensor)
# tf.consta

# 创建随机张量



<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[9, 9, 9],
       [9, 9, 9]], dtype=int32)>

In [10]:
# 创建随机数张量--正态分布
# tf.random(shape,mean,stddev,dtype)
# shape 形状
# mean  均值
# stddev  标砖差
# dtype  元素数据类型
# 如果均值和标准差省略时，默认为标准正态分布。均值为0

# 创建一个2X2的张量，其元素服从标准正态分布的张量。
tf.random.normal([2,2])



<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.5468354 , -0.6417648 ],
       [-0.17949931,  0.847687  ]], dtype=float32)>

In [ ]:
# 类似于