In [1]:
# 端到端的开源的机器学习框架
# 机器学习生态系统

# 
# 2011：Disbelief
# 2017.2 Tensorflow1.0  高层API、将Keras库整合进启动
# 

import tensorflow as tf
# keras有两类keras。我们可以自己进行选择，使用ts-keras还是keras。
# import keras
from tensorflow import keras
import numpy as np

# 我们先进行打印一下我们所有的依赖库的版本号
print(tf.__version__)
# 
print("Tensorflow运行在：",tf.executing_eagerly())


2.5.0
Tensorflow运行在： True


In [6]:
# 改变张量的形状
# tf.reshape(tensor,shape)
# tensor改变形状张量
# shape：改变之后的形状

a = tf.range(24)
tf.reshape(a,[2,3,4])

# 第二种方法
b = tf.constant(np.arange(24).reshape(2,3,4))


# shape参数=-1的话，表示这个维度上长度不确定，需要根据张量总个数和其他维度自动推导出长度
tf.reshape(b,[4,-1])




<tf.Tensor: shape=(4, 6), dtype=int64, numpy=
array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])>

In [7]:
# 多维张量的轴：张量的维度。
# 一维张量一个轴
# 二维张量两个轴
# 三位张量三个轴


In [11]:
# 增加和删除维度
# 增加维度
# tf.expand_dims(input,axis)
# 增加的这个维度，长度为1

t=tf.constant([1,2])
print(t.shape)

t1 = tf.expand_dims(t,1)
print(t1.shape)

t1

(2,)
(2, 1)


<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[1],
       [2]], dtype=int32)>

In [12]:
# 删除维度
# 删除维度：只能删除长度为1的维度
# tf.squeeze(input,axis)

In [25]:
# 交换维度
# tf.transpose(input,perm)

x=tf.constant([[1,2,3],[4,5,6]])
x
# 从输出我们可以看到张量x是一个2行3列的二维数组

tf.transpose(x)
# 从日志我们可以看到。交换维度之后，原来2行3列的二维数组。
# 变成3行2列的二维数组了。


# 第二个参数：perm
# 可以通过第二个参数调整轴的顺序.相当于我们交换了第0个轴和第一个轴的顺序
# 也相当于发生了转置
a = tf.transpose(x,perm=[1,0])
a
# <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
# array([[1, 4],
#        [2, 5],
#        [3, 6]], dtype=int32)>

# 我们继续看一下三维数组例子
# 长度为24的一维张量（矩阵）
b = tf.range(24)
b
# <tf.Tensor: shape=(24,), dtype=int32, numpy=
# array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
#        17, 18, 19, 20, 21, 22, 23], dtype=int32)>
# 进行维度变换为三维矩阵
#三位矩阵：2层、3行、4列
c=tf.reshape(b,[2,3,4])
c

# 第二个参数：perm
# 可以通过第二个参数调整轴的顺序.相当于我们交换了第0个轴和第一个轴的顺序
tf.transpose(c,(1,0,2))
'''
<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]], dtype=int32)>
'''    
# 交换维度，不仅改变了张量的视图、也改变了张量的存储顺序

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]], dtype=int32)>

In [28]:
# 张量的拼接和分割
# 拼接张量
# tf.concat(tensors,axis)

t1 = tf.constant([[1,2,3],[4,5,6]])
t2 = tf.constant([[7,8,9],[10,11,12]])
tf.concat([t1,t2],0)
'''
<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>
'''

tf.concat([t1,t2],1)
'''
<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]], dtype=int32)>
'''

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]], dtype=int32)>

In [33]:
# 分割张量
# 分割张量：就是将一个张量拆分成多个张量。分割后的张量维度不变
# tf.split(value,nums,axis=0)
# nums 为一个整数时，为等分割成nums个常量
# nums为一个列表时候，就表示不等分割成列表长度的张量。如：[1,2,1] 表示分割成是三个张量，长度分别为1，2，3
x = tf.range(24)
x = tf.reshape(x,[4,6])
x

tf.split(x,2,0)
# 分割完成之后，就是两个2行6列的矩阵张量

# 我们不等分割成三个张量
tf.split(x,[1,2,1],0)
'''
[<tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[0, 1, 2, 3, 4, 5]], dtype=int32)>,
 <tf.Tensor: shape=(2, 6), dtype=int32, numpy=
 array([[ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]], dtype=int32)>,
 <tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[18, 19, 20, 21, 22, 23]], dtype=int32)>]
'''

tf.split(x,[1,4,1],1)
'''
[<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
 array([[ 0],
        [ 6],
        [12],
        [18]], dtype=int32)>,
 <tf.Tensor: shape=(4, 4), dtype=int32, numpy=
 array([[ 1,  2,  3,  4],
        [ 7,  8,  9, 10],
        [13, 14, 15, 16],
        [19, 20, 21, 22]], dtype=int32)>,
 <tf.Tensor: shape=(4, 1), dtype=int32, numpy=
 array([[ 5],
        [11],
        [17],
        [23]], dtype=int32)>]
'''
# 张量的分割和拼接，改变了张量的视图，但是张量的存储顺序并没有发生改变

[<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
 array([[ 0],
        [ 6],
        [12],
        [18]], dtype=int32)>,
 <tf.Tensor: shape=(4, 4), dtype=int32, numpy=
 array([[ 1,  2,  3,  4],
        [ 7,  8,  9, 10],
        [13, 14, 15, 16],
        [19, 20, 21, 22]], dtype=int32)>,
 <tf.Tensor: shape=(4, 1), dtype=int32, numpy=
 array([[ 5],
        [11],
        [17],
        [23]], dtype=int32)>]