In [2]:
import torch
# 创建一个空值矩阵
x = torch.empty(5, 3)
x


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [3]:
# 创建一个
x = torch.rand(5,3)
x

tensor([[0.0486, 0.7700, 0.1534],
        [0.4570, 0.8858, 0.8331],
        [0.4942, 0.2786, 0.2646],
        [0.7937, 0.0153, 0.8188],
        [0.6796, 0.5543, 0.4568]])

In [4]:
 # 创建一个
x = torch.zeros(5,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [5]:
 # 创建一个tensor. tensor才是torch中使用的格式
x = torch.tensor([5,3])
x

tensor([5, 3])

In [6]:
# 创建一个
x = x.new_ones(5,3,dtype=torch.double)

x = torch.randn_like(x,dtype=torch.double)

x

x.size()

torch.Size([5, 3])

In [7]:
# torch可以和numpy的进行协同操作
a = torch.ones(5)
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [8]:
# torch的基本计算方法
y = torch.rand(5,3)

x+y


tensor([[ 0.1823,  1.2164,  1.9930],
        [ 1.9216,  0.2202, -1.0335],
        [ 0.9442,  0.0333,  0.6189],
        [-0.2000, -1.5920, -0.8786],
        [ 0.5970,  1.0875,  0.2083]], dtype=torch.float64)

In [9]:
torch.add(x,y)

tensor([[ 0.1823,  1.2164,  1.9930],
        [ 1.9216,  0.2202, -1.0335],
        [ 0.9442,  0.0333,  0.6189],
        [-0.2000, -1.5920, -0.8786],
        [ 0.5970,  1.0875,  0.2083]], dtype=torch.float64)

In [ ]:
### view操作可以改变矩阵维度

In [10]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) 
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [ ]:
### 与Numpy的协同操作

In [11]:
a = torch.ones(5)
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [12]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)