torch框架给我们干的最厉害的就是帮我们把反向传播计算完毕

In [1]:
import torch

# 方法一
x = torch.randn(3, 4, requires_grad=True)
x

tensor([[-0.0766, -0.1086,  1.0020,  0.2397],
        [-1.5528, -1.2045,  1.3630,  0.0702],
        [ 0.9501, -1.6347, -0.6125,  0.7322]], requires_grad=True)

In [8]:
x = torch.randn(3,4)
x.requires_grad = True
x


tensor([[-1.8439, -0.2364,  0.4021,  0.7486],
        [ 0.4580,  0.3421, -0.0565, -1.5539],
        [-0.2074, -1.0944, -0.2195, -0.4616]], requires_grad=True)

In [9]:
b=torch.randn(3,4,requires_grad=True)

In [10]:
t = x + b

In [11]:
y = t.sum()
y

tensor(-6.5268, grad_fn=<SumBackward0>)

In [12]:
y.backward()

In [13]:
b.grad

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])